WeiShop.Web/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WeiShopModel;

namespace WeiShop.Web.Models
{
    public class HomeViewModel
    {
        public int NoticeNum { get; set; }
        public IEnumerable<Banner> Banners { get; set; }
        public IEnumerable<Notice> Notices { get; set; }
        public IEnumerable<Product> Products { get; set; }

        public Product Product { get; set; }
      
        public IEnumerable<Sort> Sorts { get; set; }

        public IEnumerable<ShoppingCart> ShopCars { get; set; }
        public ShoppingCart Shopcar { get; set; }
    }
}

WeiShop.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeiShopModel;
using WeiShop.IService;
using WeiShop.Web.Models;

namespace WeiShop.Web.Controllers
{
    public class HomeController : Controller
    {
        public IBannerService BannerService { get; set; }
        public INoticeService NoticeService { get; set; }
        public IProductService ProductService { get; set; }
        public ActionResult Index()
        {
            HomeViewModel homeViewModel=new HomeViewModel();
            homeViewModel.NoticeNum = NoticeService.GetCount(n => true);
            homeViewModel.Notices = NoticeService.GetEntitiesByPage(3, 1, false, n => true, n => n.ModiTime);
            homeViewModel.Banners = BannerService.GetEntities(b => true);
            homeViewModel.Products = ProductService.GetEntitiesByPage(3, 1, false, p => p.Type == 1, p => p.ModiTime);

            return View(homeViewModel);
        }

        public ActionResult Ggxiang()
        {
            return View();
        }

        public ActionResult Gonggao()
        {
            return View();
        }
    }
}

WeiShop.Web/Controllers/ShopCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeiShop.IService;
using WeiShop.Web.Models;
using WeiShopModel;

namespace WeiShop.Web.Controllers
{
    public class ShopCarController : Controller
    {
        public IShopCarService ShopCarService { get; set; }
        public ShoppingCart Shopcar { get; set; }
        // GET: ShopCar
        public ActionResult Index()
        {
            HomeViewModel homeViewModel=new HomeViewModel();
            homeViewModel.ShopCars = ShopCarService.GetEntities(s => true);
            return View(homeViewModel);
        }
        /// <summary>
        /// 加入购物车
        /// </summary>
        /// <param name="procode">商品ID</param>
        /// <param name="qty">加入商品的数量</param>
        /// <returns></returns>
        public ActionResult AddShopCar(string procode,int qty)
        {
            ShoppingCart shopCart=new ShoppingCart();
            shopCart.CusId = 1;//用户的ID
            shopCart.ProCode = procode;
            shopCart.Qty = qty;
            shopCart.CreateTime = DateTime.Now;
            try
            {
                bool zt = ShopCarService.Add(shopCart);
                var msg = zt ? 1 : 0;
                return Content("商品添加成功!" );
            }
            catch (Exception )
            {
                return Content("此商品已存在，请到购物车编辑！");
            }
           
        }
    }
}

WeiShop.Web/Controllers/SortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeiShop.IService;
using WeiShop.Web.Models;

namespace WeiShop.Web.Controllers
{
    public class SortController : Controller
    {
        public ISortService SortService { get; set; }
        public IProductService ProductService { get; set; }
        public ActionResult Index()
        {
            HomeViewModel homeViewModel=new HomeViewModel();
            homeViewModel.Sorts = SortService.GetEntities(s =>true);
            return View(homeViewModel);
        }

        public ActionResult ProductList()
        {
            HomeViewModel homeViewModel=new HomeViewModel();
            homeViewModel.Products = ProductService.GetEntities(p => true);
            return View(homeViewModel);
        }

        public ActionResult ProductDetail(string proCode)
        {
            HomeViewModel homeViewModel=new HomeViewModel();
            homeViewModel.Product = ProductService.GetEntity(p =>p.Code==proCode);
            return View(homeViewModel);
        }
    }
}

WeiShop.Web/Controllers/UserCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeiShop.Web.Controllers
{
    public class UserCenterController : Controller
    {
        // GET: User
        public ActionResult Index()//个人中心
        {
            return View();
        }

        public ActionResult MyOrder()//全部订单
        {
            return View();
        }

        public ActionResult NoPay()//待付款
        {
            return View();
        }
    }
}

WeiShop.Web/Views/Home/Ggxiang.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>公告详情</title>
    <link href="~/Content/css/Cbase.css" type="text/css" rel="stylesheet">
    <link href="~/Content/css/index.css" type="text/css" rel="stylesheet">
    <script src="~/Scripts/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/base.js" type="text/javascript"></script>
    <script src="~/Scripts/index.js" type="text/javascript"></script>

</head>
<body>
<!--ftop开始-->
<div class="ftop"> <a class="back" onClick="javascript:history.back(-1);"><img src="~/Content/images/icon_03.png"></a>
    <h2>公告详情</h2>
    <a class="comea">&nbsp;</a>
    <div style="clear: both;"></div>
</div>
<!--ftop开始--> 
<div class="notice noti">
    <div class="notice_xq">
        <h2><span>关于国庆发货通知</span><i>2016.03.04</i></h2>
        <div class="notice_text">
            冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。冬虫夏草可以增强机体的免疫力，滋补肺肾，对肺癌、肝癌等有明显的抑制作用。在临床上对肺虚久咳，气喘，肺结核咯血，盗汗，肾虚腰膝酸痛，阳痿遗精，神经衰弱及化疗、放疗后的红细胞下降都有疗效[1]  。
            <br><br><img src="~/Content/images/img_09.jpg"><img src="~/Content/images/img_09.jpg"><br>
            冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。冬虫夏草可以增强机体的免疫力，滋补肺肾，对肺癌、肝癌等有明显的抑制作用。在临床上对肺虚久咳，气喘，肺结核咯血，盗汗，肾虚腰膝酸痛，阳痿遗精，神经衰弱及化疗、放疗后的红细胞下降都有疗效[1]  。
        </div>
    </div></div>
</body>
</html>

WeiShop.Web/Views/Home/Gonggao.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Gonggao</title>
</head>
<body>
<!--ftop开始-->
<div class="ftop"> <a class="back" onClick="javascript:history.back(-1);"><img src="~/Content/images/icon_03.png"></a>
    <h2>最新公告</h2>
    <a class="comea">&nbsp;</a>
    <div style="clear: both;"></div>
</div>
<!--ftop开始--> 
<div class="notice">
    <ul>
        <li><a href="@Url.Action("Ggxiang")">
            <h2><span>关于国庆发货通知关于国庆发货通知关于国庆发货通知关于国庆发货通知</span><i>2016.03.04</i></h2>
            <p>冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。</p></a></li>
        <li><a href="@Url.Action("Ggxiang")">
            <h2><span>关于国庆发货通知关于国庆发货通知关于国庆发货通知关于国庆发货通知</span><i>2016.03.04</i></h2>
            <p>冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。</p></a></li>
        <li><a href="@Url.Action("Ggxiang")">
            <h2><span>关于国庆发货通知关于国庆发货通知关于国庆发货通知关于国庆发货通知</span><i>2016.03.04</i></h2>
            <p>冬虫夏草又名虫草，是我国民间惯用的一种名贵滋补药材，其营养成分高于人参，可入药，也可食用，是上乘的佳肴，具有很高的营养价值。</p></a></li>
    </ul>
</div>
</body>
</html>

WeiShop.Web/Views/Home/Index.cshtml
@model WeiShop.Web.Models.HomeViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_LayoutNav.cshtml";
}

<!--ftop开始-->
<div class="ftop">
    <div class="index_search">
        <input onclick="document.location='search.html'" type="text" placeholder="请输入您要搜索的产品">
        <p><a href="@Url.Action("Gonggao")"><img src="~/Content/images/icon_05.png"><sup>@Model.NoticeNum</sup></a></p>
    </div>
    <div style="clear: both;"></div>
</div>
<!--ftop开始-->
<!--banner start-->
<div class="swiper-container index_banner">
    <div class="swiper-wrapper">
        @foreach (var banner in Model.Banners)
        {
            <div class="swiper-slide">
                <a href="@banner.Link"><img src="@banner.Image" alt=""></a>
            </div>
        }
    </div>
    <div class="swiper-pagination swiper-index"></div>
</div>

<!--banner over-->
<div class="index_knowledge">
    <img src="~/Content/images/icon_0902.png">
    <div class="swiper-container dlist">
        <div class="swiper-wrapper">
            @foreach (var notice in Model.Notices)
            {
                <a class="swiper-slide" href="@Url.Action("Ggxiang","Home",new { notice.Id})"><i>最新</i>@notice.Title</a>
            }
            

        </div>
    </div>
</div>

<div class="index_main">
    <ul>
        @foreach (var product in Model.Products)
        {
            <li>
                <a href="@Url.Action("ProductDetail", "Sort", new {proCode=product.Code})">
                    <img src="@product.ProPhotoes.FirstOrDefault(p => p.No == 0).ImgUrl">
                </a>
                <div class="product_text">
                    <h2>
                        <p>@product.Name</p>
                        <span><img src="~/Content/images/icon_06.png"><img src="~/Content/images/icon_06.png"><img src="~/Content/images/icon_06.png"><img src="~/Content/images/icon_06.png"><img src="~/Content/images/icon_07.png"></span>
                    </h2>
                    <p>@product.Intro</p>
                    <h3>
                        <p><i>￥</i><b>@product.SellPrice</b>
                        @foreach (var tag in product.Tags)
                        {
                            <span>@tag.Name</span>
                        }
                        </p>
                        <a href="product_xq.html">立即购买</a>
                    </h3>
                </div>
            </li>
        }
        
    </ul>
</div>
<div class="index_icon">
    <p>
        <span><img src="~/Content/images/icon_01.png"><i>品质保证</i></span>
        <span><img src="~/Content/images/icon_02.png"><i>送货保障</i></span>
        <span><img src="~/Content/images/icon_003.png"><i>7天包换</i></span>
        <span><img src="~/Content/images/icon_04.png"><i>质量保障</i></span>
    </p>
</div>

@section Style
{
    <link href="~/Content/css/index.css" type="text/css" rel="stylesheet">
    <link href="~/Content/css/swiper.min.css" type="text/css" rel="stylesheet">
}

@section Script
{
    <script src="~/Scripts/index.js" type="text/javascript"></script>
    <script src="~/Scripts/swiper.min.js" type="text/javascript"></script>
    <script>
	    var swiper1 = new Swiper('.index_banner', {
		    pagination: '.swiper-index',
		    paginationClickable: true,
		    loop: true,
		    autoplay: 4000
	    });

      var swiper1 = new Swiper('.dlist', {
        loop: true,
        autoplay: 4000,
        direction : 'vertical'
      });
    </script>
}

WeiShop.Web/Views/ShopCar/Index.cshtml
@using System.Activities.Statements
@model WeiShop.Web.Models.HomeViewModel
@{
    Layout = "~/Views/_LayoutNav.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/css/Cbase.css" type="text/css" rel="stylesheet">
    <link href="~/Content/css/index.css" type="text/css" rel="stylesheet">
    <link href="~/Content/css/swiper.min.css" type="text/css" rel="stylesheet">
    <script src="~/Scripts/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/base.js" type="text/javascript"></script>
    <script src="~/Scripts/swiper.min.js" type="text/javascript"></script>
    <script src="~/Scripts/index.js" type="text/javascript"></script>
</head>

<body>
    <!--ftop开始-->
    <div class="ftop">
        <h3 style=" text-align:center; font-size:18px;">购物车</h3>
        <a style="position:absolute; top:4px; font-size:14px; right:15px; color:#333" class="all">编辑</a>
        <div style="clear: both;"></div>
    </div>
    <!--ftop开始-->
    <div class="shopcar">
        <ul>        
                @foreach (var item in Model.ShopCars)
                 {
                     <li>
                         <p><label><input type="checkbox"></label>
                         <a href="@Url.Action("ProductDetail", "Sort", new {proCode = item.ProCode})">
                             <img src="@item.Product.ProPhotoes.FirstOrDefault(p => p.ProCode == item.ProCode).ImgUrl"/>
                             </a>
                         </p>
                         <div class="shop_car">
                             <a href="@Url.Action("ProductDetail", "Sort", new {proCode = item.ProCode})">@item.Product.Name</a>
                             <div class="shu">
                                 <span class="jian"><img src="~/Content/images/icon_016.png"></span>
                                 <input class="shopcart-td-num" type="text" value="@item.Qty"/>
                                 <span class="jia"><img src="~/Content/images/icon_017.png"></span>
                                 <a><i>￥</i><b>185.00</b></a>
                             </div>
                         </div>
                         <img class="delete" src="~/Content/images/icon_030.png">
                     </li>
                 }          
        </ul>
        <div class="pay">
            <label><input type="checkbox"><span>全选</span></label>
            <div class="pay_right">
                <p><span>合计：<b>￥898.50</b></span><i>不含运费</i></p>
                <a href="confirm_order.html">结算（5）</a>
            </div>
        </div>
        <!--弹窗-->
        <div class="block_bg"></div>
        <div class="delete_box">
            <h2>确定要删除此商品吗？</h2>
            <p><a class="cancel">取消</a><a class="sure">确定</a></p>
        </div>
    </div>
    <script>
	$(function(){
        var jian = $(".jian");
        var jia = $(".jia");
        var kunchun = 10; //当库存不足时，可以提醒用户。
        jia.click(function() {
            var n = $(this).siblings("input").val();
            n++;
            if (n > kunchun) {
                alert("库存不足啦!");
				$(this).siblings("input").val(kunchun - 1);
				return false;
            }
            $(this).siblings("input").val(n)
			return false;
        });
		jian.click(function() {
            var n = $(this).siblings("input").val();
            n--;
            if (n < 1) {
                $(this).siblings("input").val(n + 1);
                return false;
            }
            $(this).siblings("input").val(n)
			return false
        })

		$("label input").click(function(){
			$(this).parent().toggleClass("on");
			var flag=1;
			$("label input").each(function(){
				if(!this.checked){
					flag=0;
				}
			})
			if(flag==1){
				$(".car_pay span").addClass("on")
			}
			else{
				$(".car_pay span").removeClass("on")
			}
		})
		$(".pay label span").click(function(){
			if($(this).hasClass("on")){
				$(this).removeClass("on")
				$("label input").prop("checked",false);
				$("label").removeClass("on")
			}
			else{
				$(this).addClass("on")
				$("label input").prop("checked",true);
				$("label").addClass("on")
			}
		})

		$(".ftop .all").click(function(){
		    var val=$(this).html();
			if(val=="编辑"){
			   $(this).html("完成")
			}else{
			   $(this).html("编辑")
			}
		})

		$(".ftop .all").click(function(){
             $(".shopcar ul li .delete").toggle();
		})



		$(".shopcar ul li .delete").click(function(){
			$(".block_bg,.delete_box").fadeIn();
	    })
		$(".block_bg,.delete_box p a").click(function(){
			$(".block_bg,.delete_box").fadeOut();
	    })
    });
    </script>


</body>
</html>

WeiShop.Web/Views/Sort/Index.cshtml
@model WeiShop.Web.Models.HomeViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_LayoutNav.cshtml";
}
<link href="~/Content/css/Cbase.css" type="text/css" rel="stylesheet">
<link href="~/Content/css/index.css" type="text/css" rel="stylesheet">
<link href="~/Content/css/swiper.min.css" type="text/css" rel="stylesheet">
<script src="~/Scripts/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="~/Scripts/base.js" type="text/javascript"></script>
<script src="~/Scripts/swiper.min.js" type="text/javascript"></script>
<script src="~/Scripts/index.js" type="text/javascript"></script>

    <!--ftop开始-->
    <div class="ftop">
        <div class="index_search index_search01" style="padding-left: 10px;">
            <div style="left:0px; width:100%;" onclick="document.location='search.html'">
                <input type="text" placeholder="请输入您要搜索的产品">
                <input type="button" value=" ">
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <!--ftop开始-->
    <!--分类页面-->
    <!--分类-->
    <div class="fenlei">
    <div class="fen-nav">     
        <ul>
            @foreach (var item  in Model.Sorts.Where(s => s.Code.Length == 3))
            {
                if (item.Code=="001")
                {
                    <li class="on">@item.Name</li>
                }
                else
                {
                    <li>@item.Name</li>
                }
                   
            }
        </ul>
    </div>
        <div class="fen-box">
            <div class="fff">
                        @foreach (var item in Model.Sorts.Where(s => s.Code.Length == 3))
                        {
                            <div class="fenlist">
                                <ul>
                                @foreach (var item1 in Model.Sorts.Where(s => s.UpCode == item.Code))
                                {
                                    <li>
                                        <a class="imga" href="@Url.Action("ProductList","Sort",new {item.UpCode})"><img src="@item1.Img"></a>
                                        <a class="txta" href="@Url.Action("ProductList","Sort",new {item.UpCode})">
                                            <span>@item1.Name</span>
                                            <i>@item1.Title</i>
                                    </a>
                                </li>
                                }
                                </ul>
                            </div>
                        }

                  
        </div>
    </div>

    <!--分类-->
    <!--分类页面-->



    <script>
    var m=$(window).height()-98;
    $(".fen-nav,.fen-box").css("height",m+"px");


    var $lii = $(".fenlei .fen-nav li");
    $(".fenlei .fen-box .fenlist").hide();
    $(".fenlei .fen-box .fenlist").first().show();
    $lii.click(function(){
        var n = $(this).index();
        var h = $(this).height();
        //alert(h)
        var sunh = n * h-1;
        $(".fen-nav").animate({"scrollTop":sunh+"px"},1000)


        $(this).addClass("on").siblings().removeClass("on");
        var indexx = $lii.index(this);
        $('.fenlei .fen-box').animate({scrollTop: '0px'},500);
        $(".fenlei .fen-box .fff .fenlist").hide();
        $(".fenlei .fen-box .fff .fenlist").eq(indexx).show();
    })
    var w=$(".fenli li img").width();
    $(".fenli li img").height(w);
    $(window).resize(function(){
        var w=parseInt($(".fenli li img").width());
        $(".fenli li img").height(w);
    })

    </script>

</div>

WeiShop.Web/Views/Sort/ProductList.cshtml
@using WeiShopModel
@model WeiShop.Web.Models.HomeViewModel
@{
    ViewBag.Title = "ProductList";
    Layout = "~/Views/_LayoutMaster.cshtml";
}

<link href="~/Content/css/Cbase.css" type="text/css" rel="stylesheet">
<link href="~/Content/css/index.css" type="text/css" rel="stylesheet">
<link href="~/Content/css/swiper.min.css" type="text/css" rel="stylesheet">
<script src="~/Scripts/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="~/Scripts/base.js" type="text/javascript"></script>
<script src="~/Scripts/swiper.min.js" type="text/javascript"></script>
<script src="~/Scripts/index.js" type="text/javascript"></script>

<!--ftop开始-->
<div class="ftop">
    <div class="index_search index_search01">
        <a class="back" onClick="javascript:history.back(-1);"><img src="~/Content/images/icon_03.png"></a>
        <div>
            <input type="text" placeholder="请输入您要搜索的产品">
            <input class="dw" onclick="document.location='search_list.html'" type="button" value=" ">
        </div>
    </div>
    <div style="clear: both;"></div>
</div>
<!--ftop开始-->
<div class="search_list">
    <p><a class="on"><span>综合</span></a><a><span>销量</span></a><a><span>评价</span></a><a><span class="bg">价格</span></a></p>
    <ul>
        @foreach (var item in Model.Products)
        {
            <li>
                <a href="@Url.Action("ProductDetail","Sort",new {proCode=item.Code})">
                    <img src="@item.ProPhotoes.FirstOrDefault(p=>p.No==0).ImgUrl">
                    <div class="search_item">
                        <p>@item.Name</p>
                        <h2><i>￥</i><b>@item.SellPrice</b><span>月销18252笔</span>
                        </h2>
                    </div>
                </a>
            </li>
        }
    </ul>
</div>

<script>
    $(".search_list ul li a img").each(function(){
        var w = $(this).width();
        $(this).height(w+"px");
    })

</script>

WeiShop.Web/Views/UserCenter/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_LayoutNav.cshtml";
}
<link href="~/Content/css/center.css" type="text/css" rel="stylesheet">

<!--个人中心-->
<div class="centerindex">
    <div class="geren">
        <a class="imga"><img src="/Content/images/centericon_06.png" alt="头像"></a>
        <a class="name">Angelarbaby杨颖</a>
        <h6><span>普通用户</span><i>ID:7027</i></h6>
        <a class="seta" href="center-set.html"><img src="/Content/images/centericon_03.png" alt=""></a>
    </div>
    <div class="link">
        <div class="sg">
            <a class="biga" href="center-order.html"><span class="bg1">我的订单</span><i>查看全部订单</i></a>
            <div class="kind">
                <a href="center-order.html"><img src="/Content/images/centericon_29.png" alt=""><i>待付款</i><b>15</b></a>
                <a href="center-order.html"><img src="/Content/images/centericon_19.png" alt=""><i>待发货</i></a>
                <a href="center-order.html"><img src="/Content/images/centericon_22.png" alt=""><i>待收货</i></a>
                <a href="center-order.html"><img src="/Content/images/centericon_24.png" alt=""><i>待评价</i></a>
                <a href="center-order-return.html"><img src="/Content/images/centericon_26.png" alt=""><i>退款/售后</i></a>
            </div>
        </div>
        <div class="sg">
            <a class="biga"><span class="bg2">我的钱包</span></a>
            <div class="both">
                <a href="center-income.html"><span><b>15025</b>元</span><i>账户余额</i></a>
                <a href="center-code.html"><span><img src="/Content/images/centericon_40.png" alt=""></span><i>我的二维码</i></a>
            </div>
        </div>
        <div class="sg">
            <a class="biga bg" href="center-address.html"><span class="bg4">地址管理</span></a>
            <a class="biga bg" href="center-collect.html"><span class="bg5">我的收藏</span></a>
            <a class="biga bg" href="center-mind.html"><span class="bg6">意见反馈</span></a>
            <a class="biga bg" href="center-contact.html"><span class="bg7">联系我们</span></a>
        </div>
    </div>
</div>
<!--个人中心-->

WeiShop.Web/Views/UserCenter/NoPay.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NoPay</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

WeiShop.Web/Views/_LayoutMaster.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/Cbase.css" type="text/css" rel="stylesheet">  
    @RenderSection("Style",false)
    <script src="~/Scripts/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/base.js" type="text/javascript"></script>
</head>

<body>
    @RenderBody()


    @RenderSection("Script",false)
    
</body>
</html>

WeiShop.Web/Views/_LayoutNav.cshtml
@using WeiShop.Web.Controllers
@{
    Layout = "_LayoutMaster.cshtml";
}

@section Style
{
    @RenderSection("Style",false)
}

@section Script
{
    @RenderSection("Script",false)
}

@RenderBody()
<!--fixft开始-->
<div class="fixft">
    <a href="@Url.Action("Index","Home")" class="current">
        <span><img src="~/Content/images/navicon_45.png" class="img1"><img src="~/Content/images/navicon_28.png" class="img2"></span>
        <i>首页</i>
    </a>
    <a href="@Url.Action("Index","Sort")">
        <span><img src="~/Content/images/navicon_48.png" class="img1"><img src="~/Content/images/navicon_30.png" class="img2"></span>
        <i>分类</i>
    </a>
    <a href="@Url.Action("Index","ShopCar")">
        <span><img src="~/Content/images/navicon_50.png" class="img1"><img src="~/Content/images/navicon_32.png" class="img2"><em>12</em></span>
        <i>购物车</i>
    </a>
    <a href="@Url.Action("Index","UserCenter")">
        <span><img src="~/Content/images/navicon_42.png" class="img1"><img src="~/Content/images/navicon_35.png" class="img2"></span>
        <i>我的</i>
    </a>
</div>
<!--fixft结束-->